-- MySQL Script generated by MySQL Workbench
-- Wed Sep  2 12:49:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(124) NOT NULL,
  `active` TINYINT NOT NULL,
  `category_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_category_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `price` DECIMAL(65,2) UNSIGNED NOT NULL,
  `dph` INT UNSIGNED NOT NULL,
  `active` BIT(2) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_adress` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(256) NULL,
  `last_name` VARCHAR(256) NULL,
  `firm_name` VARCHAR(256) NULL,
  `street` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `country` VARCHAR(256) NOT NULL,
  `zipcode` VARCHAR(12) NOT NULL,
  `DIC` VARCHAR(45) NOT NULL,
  `IC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shipping_adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipping_adress` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(256) NULL,
  `last_name` VARCHAR(256) NULL,
  `firm_name` VARCHAR(256) NULL,
  `street` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `country` VARCHAR(256) NOT NULL,
  `zipcode` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(65,2) NOT NULL,
  `price_without_dph` DECIMAL(65,2) UNSIGNED NOT NULL,
  `invoice_number` INT UNSIGNED NOT NULL,
  `datum_vystaveni` DATE NOT NULL,
  `datum_zdanitelneho_plneni` DATE NOT NULL,
  `datum_splatnosti` DATE NOT NULL,
  `invoice_adress_id` INT UNSIGNED NOT NULL,
  `shipping_adress_id` INT UNSIGNED NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_invoice_adress1_idx` (`invoice_adress_id` ASC) VISIBLE,
  INDEX `fk_order_shipping_adress1_idx` (`shipping_adress_id` ASC) VISIBLE,
  UNIQUE INDEX `invoice_number_UNIQUE` (`invoice_number` ASC) VISIBLE,
  CONSTRAINT `fk_order_invoice_adress1`
    FOREIGN KEY (`invoice_adress_id`)
    REFERENCES `mydb`.`invoice_adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_shipping_adress1`
    FOREIGN KEY (`shipping_adress_id`)
    REFERENCES `mydb`.`shipping_adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_order` (
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `price` DECIMAL(65,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_product_has_order_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_has_order_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_order_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eshop_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eshop_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firm_name` VARCHAR(256) NOT NULL,
  `street` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `country` VARCHAR(256) NOT NULL,
  `zipcode` VARCHAR(12) NOT NULL,
  `DIC` VARCHAR(45) NOT NULL,
  `IC` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `data_type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image_has_product` (
  `image_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`image_id`, `product_id`),
  INDEX `fk_image_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_image_has_product_image1_idx` (`image_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_has_product_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `mydb`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
