<header>
    <h1>Domovská stránka</h1>
</header>
<section>
    <h2><?= $uploadMessage ?></h2>
    <div class="custom-file">
        <form method="post" enctype="multipart/form-data">
            Select image to upload:
            <input id="my-input" class="custom-file-input" type="file" name="upfile" id="fileToUpload">
            <label for="my-input" class="custom-file-label">SOUBOR</label>
            <input type="submit" value="Upload Image" name="submit">
        </form>
    </div>
</section>