<header>
    <h1>Domovská stránka</h1>
</header>
<section>
    <h2><?=$_uploadMessage ?></h2>
    <div class="custom-file">
        <form method="post" enctype="multipart/form-data">
            <input id="my-input" class="custom-file-input" type="file" name="upfile">
            <label for="my-input" class="custom-file-label">SOUBOR</label><br>
            <input id="my-input2" class="custom-file-input" type="file" name="upfile2">
            <label for="my-input2" class="custom-file-label">SOUBOR2</label><br>
            <input id="my-input3" class="custom-file-input" type="file" name="upfile3">
            <label for="my-input3" class="custom-file-label">SOUBOR3</label><br>
            <input type="submit" value="Upload Image" name="submit">
        </form>
    </div>
</section>