<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/eshopZaklad" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keywords ?>" />
    <link rel="stylesheet" href="style.css?v=<?=time()?>" type="text/css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="home">Eshop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <?php foreach ($mainCategories as $mainCategory) : ?>
                        <?php if (!empty($subCategories[$mainCategory["id"]])) : ?>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown<?= $mainCategory["name"] ?>" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <?= $mainCategory["name"] ?>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown<?= $mainCategory["name"] ?>">
                                    <?php foreach ($subCategories[$mainCategory["id"]] as $subCategory) :
                                    ?>
                                        <a class="dropdown-item" href="category/<?= $subCategory["dash_name"] ?>">
                                            <img src="images/category/thumbnail/<?= $subCategory["image"] ?>" alt="" height="50" width="50">
                                            <?= $subCategory["name"] ?>
                                        </a>
                                    <?php endforeach; ?>
                                </div>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="category/<?= $mainCategory["dash_name"] ?>"><?= $mainCategory["name"] ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>

                </ul>
            </div>
        </nav>
    </header>

    <article>
        <?php $this->controller->writeView(); ?>
    </article>

    <footer>

    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha2/js/bootstrap.min.js"></script>
</body>

</html>